<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mycodebot</name>
  <version>0.0.1</version>
  <description>TODO: Package description</description>
  <maintainer email="mycode@todo.todo">mycode</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclpy</depend>
  <depend>pycodemsg</depend>
 
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
