<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pycodeaudio</name>
  <version>1.0.0</version>
  <description>Audio app for ros2</description>
  <maintainer email="tech@pycodeworld.com">pycodeworld</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>pycodemsg</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
